// Mock data for the restaurant management system

export interface User {
  id: string;
  email: string;
  password: string;
  firstName: string;
  lastName: string;
  role: 'student' | 'employee' | 'manager' | 'admin';
  loyaltyPoints: number;
  referralCode?: string; // Unique referral code for customers
  referredBy?: string; // ID of user who referred this customer
  position?: 'employee' | 'manager'; // For employees and managers
  status?: 'active' | 'inactive'; // For employees and managers
  createdAt?: Date; // Date when account was created
  lastLogin?: Date; // Last login time
  lastLogout?: Date; // Last logout time
  timeSpent?: number; // Total time spent in app (in milliseconds)
  loginHistory?: Array<{login: Date, logout?: Date}>; // Login history
}

export interface MenuItem {
  id: string;
  name: string;
  category: 'starter' | 'main' | 'drink';
  price: number;
  description: string;
  image: string;
  available: boolean;
  inStock: boolean;
  isDishOfTheDay?: boolean; // Plat du jour
}

export interface DailyMenu {
  id: string;
  date: string; // Format: YYYY-MM-DD
  starters: string[]; // IDs des entrées (max 4)
  mains: string[]; // IDs des plats principaux (max 4)
  drinks: string[]; // IDs des boissons (max 4)
  createdBy: string; // ID de l'employé
  createdAt: Date;
}

export interface Order {
  id: string;
  customerId: string;
  customerName: string;
  customerAddress: string;
  items: { menuItemId: string; quantity: number; itemName: string; price: number }[];
  total: number;
  status: 'pending' | 'in-preparation' | 'in-delivery' | 'delivered' | 'cancelled';
  timestamp: Date;
  paymentStatus: 'pending' | 'paid';
}

export interface Complaint {
  id: string;
  customerId: string;
  customerName: string;
  subject: string;
  message: string;
  timestamp: Date;
  status: 'pending' | 'responded' | 'resolved';
  employeeResponse?: string;
  managerResponse?: string;
  adminResponse?: string;
  responseValidated: boolean;
}

export interface Event {
  id: string;
  name: string;
  description: string;
  date: Date;
  participants: string[];
  maxParticipants: number;
}

export interface Employee {
  id: string;
  firstName: string;
  lastName: string;
  position: 'cook' | 'server' | 'delivery';
  status: 'active' | 'on-leave' | 'sick-leave';
  email: string;
  phone: string;
  hireDate: Date;
}

// Initial mock data
export const mockUsers: User[] = [
  {
    id: '2',
    email: 'okddominique@zeduc.employe.com',
    password: '123@',
    firstName: 'Dominique',
    lastName: 'Ockiere',
    role: 'employee',
    loyaltyPoints: 0,
    position: 'employee',
    status: 'active',
    createdAt: new Date('2024-01-15'),
    timeSpent: 0,
    loginHistory: [],
  },
  {
    id: '3',
    email: 'dominiqueockiere@zeduc.manager.com',
    password: '123@',
    firstName: 'Dominique',
    lastName: 'Ockiere',
    role: 'manager',
    loyaltyPoints: 0,
    position: 'manager',
    status: 'active',
    createdAt: new Date('2024-01-15'),
    timeSpent: 0,
    loginHistory: [],
  },
  {
    id: '4',
    email: 'dominique.ockiere@zeduc.admin.com',
    password: '123@',
    firstName: 'Dominique',
    lastName: 'Ockiere',
    role: 'admin',
    loyaltyPoints: 0,
  },
];

export const mockMenuItems: MenuItem[] = [
  // Starters - Entrées
  {
    id: 'm1',
    name: 'Beignets de Douala',
    category: 'starter',
    price: 1500,
    description: 'Beignets dorés et moelleux, spécialité de Douala',
    image: '/data/images/entree_beignets-de-manioc-douala.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm2',
    name: 'Accra de Haricots Yaoundé',
    category: 'starter',
    price: 2000,
    description: 'Beignets de haricots noirs épicés, tradition de Yaoundé',
    image: '/data/images/entree_accra-de-haricots-yaounde.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm3',
    name: 'Plantain Frit Bafoussam',
    category: 'starter',
    price: 1800,
    description: 'Plantain mûr frit à la perfection, délice de Bafoussam',
    image: '/data/images/entree_plantain-frit-bafoussam.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm13',
    name: 'Sanga de Maïs Bafang',
    category: 'starter',
    price: 2200,
    description: 'Boulettes de maïs et d\'arachides grillées, spécialité de Bafang',
    image: '/data/images/plat_sanga-de-mais-bafang.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm21',
    name: 'Crevettes Pili-Pili',
    category: 'starter',
    price: 2400,
    description: 'Crevettes grillées au piment pili-pili, saveur authentique',
    image: '/data/images/entree_crevettes-pili-pili.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm22',
    name: 'Samosas Camerounais',
    category: 'starter',
    price: 1700,
    description: 'Samosas farcis aux légumes et épices locales',
    image: '/data/images/entree_samosas-camerounais.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm23',
    name: 'Beignets de Poisson',
    category: 'starter',
    price: 2100,
    description: 'Beignets de poisson frais avec sauce piquante',
    image: '/data/images/entree_beignets-de-poisson.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm24',
    name: 'Salade de Fruits Tropicaux',
    category: 'starter',
    price: 1500,
    description: 'Mélange de fruits tropicaux frais du Cameroun',
    image: '/data/images/entree_salade-de-fruits-tropicaux.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm25',
    name: 'Soupe de Pistache Africaine',
    category: 'starter',
    price: 2000,
    description: 'Soupe crémeuse aux graines de pistache africaine',
    image: '/data/images/entree_soupe-de-pistache-africaine.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm26',
    name: 'Brochettes de Bœuf',
    category: 'starter',
    price: 2300,
    description: 'Brochettes de bœuf marinées aux épices camerounaises',
    image: '/data/images/plat_brochettes-de-boeuf.png',
    available: true,
    inStock: true,
  },

  {
    id: 'm46',
    name: 'Akwan de Maïs Douala',
    category: 'starter',
    price: 1600,
    description: 'Boulettes de maïs grillées, spécialité de Douala',
    image: '/data/images/entree_akwan-de-mais-douala.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm47',
    name: 'Salade de Tomates Yaoundé',
    category: 'starter',
    price: 1400,
    description: 'Salade fraîche de tomates locales avec vinaigrette',
    image: '/data/images/entree_salade-de-tomates-yaounde.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm48',
    name: 'Boulettes de Viande Bafoussam',
    category: 'starter',
    price: 2200,
    description: 'Boulettes de viande hachée aux épices locales',
    image: '/data/images/entree_boulettes-de-viande-bafoussam.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm49',
    name: 'Chips de Manioc Kribi',
    category: 'starter',
    price: 1600,
    description: 'Chips de manioc croustillantes, spécialité de Kribi',
    image: '/data/images/entree_chips-macabo.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm50',
    name: 'Salade de Concombre',
    category: 'starter',
    price: 1300,
    description: 'Salade fraîche de concombre avec vinaigrette légère',
    image: '/data/images/entree_salade-de-concombre-camerounais.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm61',
    name: 'Beignets de Banane Plantain',
    category: 'starter',
    price: 1600,
    description: 'Beignets croustillants de banane plantain mûre, douceur camerounaise',
    image: '/data/images/entree_beignets-de-manioc-douala.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm62',
    name: 'Soupe de Gombo Ngaoundéré',
    category: 'starter',
    price: 1900,
    description: 'Soupe traditionnelle au gombo frais de Ngaoundéré',
    image: '/data/images/entree_soupe-de-legumes-traditionnelle.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm67',
    name: 'Calamars Grillés',
    category: 'starter',
    price: 2500,
    description: 'Calamars frais grillés avec sauce piquante et citron',
    image: '/data/images/entree_brochette-crevette.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm68',
    name: 'Salade de Fruits de Mer',
    category: 'starter',
    price: 2200,
    description: 'Mélange de fruits de mer frais avec vinaigrette légère',
    image: '/data/images/entree_salade-de-fruits-tropicaux.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm69',
    name: 'Beignets Haricot',
    category: 'starter',
    price: 800,
    description: 'Duo classique : beignets dorés et haricots mijotés, touche d’oignon doux.',
    image: '/data/images/entree_beignet-haricot.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm70',
    name: 'Accra de morue ',
    category: 'starter',
    price: 1000,
    description: 'Boulettes croustillantes de morue assaisonnées aux épices du Littoral.',
    image: '/data/images/entree_accra-morue.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm71',
    name: 'Ndolé en verrine',
    category: 'starter',
    price: 900,
    description: 'Mini-verrine de ndolé fondant à la pâte d’arachide et crevette fumée.',
    image: '/data/images/entree_verrine-ndole.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm72',
    name: 'Brochette de plantain et crevette',
    category: 'starter',
    price: 1100,
    description: 'Mignardises grillées caramélisées, alliance sucré-salé parfaite.',
    image: '/data/images/entree_brochette-crevette.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm73',
    name: 'Chips de macabo',
    category: 'starter',
    price: 700,
    description: 'Fines tranches croustillantes au paprika et sel fin.',
    image: '/data/images/entree_chips-macabo.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm74',
    name: 'Mini poisson braisé',
    category: 'starter',
    price: 1200,
    description: 'Petit poisson fumé épicé et citronné, une explosion de goût.',
    image: '/data/images/entree_mini-poisson.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm75',
    name: 'Salade camerounaise',
    category: 'starter',
    price: 800,
    description: 'Tomate, oignon, avocat, thon et vinaigrette de banane.',
    image: '/data/images/entree_salade-camerounaise.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm76',
    name: 'Koki express',
    category: 'starter',
    price: 900,
    description: 'Petit gâteau de haricot jaune, vapeur dans feuille de bananier.',
    image: '/data/images/entree_koki.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm77',
    name: 'Puff-Puff ',
    category: 'starter',
    price: 600,
    description: 'Petits beignets parfumés au poivre de Penja.',
    image: '/data/images/entree_puff-poivre.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm78',
    name: 'Crêpe salée gari-sardine',
    category: 'starter',
    price: 800,
    description: 'La crêpe façon 237 – sardine, gari et épices locales.',
    image: '/data/images/entree_crepe-gari.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm79',
    name: 'Frites de plantain sucré',
    category: 'starter',
    price: 600,
    description: 'Plantains caramélisés et croustillants à souhait.',
    image: '/data/images/entree_frites-plantain.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm80',
    name: 'Mini bouillon de bœuf',
    category: 'starter',
    price: 1000,
    description: 'Délicieuse soupe épicée pour éveiller les papilles.',
    image: '/data/images/plat_bouillon-boeuf.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm81',
    name: 'Soupe de gombo',
    category: 'starter',
    price: 900,
    description: 'Velouté d’okra frais, relevé au piment doux.',
    image: '/data/images/entree_soupe-gombo.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm82',
    name: 'Ndolé royal',
    category: 'starter',
    price: 2500,
    description: 'feuilles amères, pâte d’arachide, crevettes fumées, plantain mûr.',
    image: '/data/images/plat_ndole-royal.png',
    available: true,
    inStock: true,
  },

  // Mains - Plats principaux
  {
    id: 'm4',
    name: 'Ndolé aux Arachides',
    category: 'main',
    price: 3500,
    description: 'Plat traditionnel aux feuilles de ndolé et sauce arachides',
    image: '/data/images/plat_ndole-royal.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm5',
    name: 'Eru au Poisson Fumée',
    category: 'main',
    price: 4000,
    description: 'Feuilles d\'eru mijotées avec poisson fumé et huile de palme',
    image: '/data/images/plat_eru-au-poisson-fume.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm6',
    name: 'Koki de Haricots Bafia',
    category: 'main',
    price: 2500,
    description: 'Gâteau de haricots noirs cuit à la vapeur, tradition de Bafia',
    image: '/data/images/plat_koki-de-haricots-bafia.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm7',
    name: 'Poulet DG Traditionnel',
    category: 'main',
    price: 5000,
    description: 'Poulet mijoté aux épices et légumes, plat prestigieux',
    image: '/data/images/plat_poulet-dg-traditionnel.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm8',
    name: 'Poisson Braisé Kribi',
    category: 'main',
    price: 4500,
    description: 'Poisson frais braisé aux légumes et épices locales',
    image: '/data/images/plat_poisson-braise-kribi.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm14',
    name: 'Plantain Pilé',
    category: 'main',
    price: 3800,
    description: 'Banane plantain pilée accompagnée de sauce aux arachides',
    image: '/data/images/plat_plantain-pile.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm15',
    name: 'Nkui',
    category: 'main',
    price: 3200,
    description: 'Spécialité camerounaise aux feuilles de ndolé et arachides',
    image: '/data/images/plat_nkui.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm29',
    name: 'Riz aux Feuilles de Manioc',
    category: 'main',
    price: 2800,
    description: 'Riz parfumé mijoté avec feuilles de manioc et huile de palme',
    image: '/data/images/plat_riz-aux-feuilles-de-manioc.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm30',
    name: 'Bœuf Sauté aux Épices',
    category: 'main',
    price: 4100,
    description: 'Bœuf sauté aux épices camerounaises et légumes frais',
    image: '/data/images/plat_boeuf-saute-aux-epices.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm31',
    name: 'Grillades Mixtes Camerounaises',
    category: 'main',
    price: 4800,
    description: 'Assortiment de viandes grillées aux épices et condiments locaux',
    image: '/data/images/plat_grillades-mixtes-camerounaises.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm32',
    name: 'Couscous de Mil Rouge',
    category: 'main',
    price: 3500,
    description: 'Couscous de mil rouge avec légumes et sauce aux arachides',
    image: '/data/images/plat_couscous-de-mil-rouge.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm33',
    name: 'Taro aux Épinards',
    category: 'main',
    price: 3300,
    description: 'Taro cuit avec épinards frais et huile de palme',
    image: '/data/images/plat_taro.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm34',
    name: 'Ragoût de Chèvre',
    category: 'main',
    price: 3900,
    description: 'Chèvre mijotée aux légumes et épices traditionnelles',
    image: '/data/images/plat_ragout-de-chevre.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm55',
    name: 'Poulet aux Noix de Cajou',
    category: 'main',
    price: 4200,
    description: 'Poulet sauté aux noix de cajou et légumes croquants',
    image: '/data/images/plat_poulet-aux-noix-de-cajou.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm56',
    name: 'Poisson aux Légumes Verts',
    category: 'main',
    price: 4300,
    description: 'Poisson frais mijoté avec légumes verts et huile de palme',
    image: '/data/images/plat_poisson-aux-legumes-verts.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm63',
    name: 'Poulet Yassa Traditionnel',
    category: 'main',
    price: 4400,
    description: 'Poulet mariné au citron et oignons, spécialité sénégalo-camerounaise',
    image: '/data/images/plat_poulet-yassa-traditionnel.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm64',
    name: 'Riz au Curry de Crevettes',
    category: 'main',
    price: 4600,
    description: 'Riz parfumé au curry avec crevettes fraîches et légumes',
    image: '/data/images/plat_riz-au-curry-de-crevettes.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm69',
    name: 'Agouti Rôti aux Épices',
    category: 'main',
    price: 4700,
    description: 'Agouti rôti aux épices traditionnelles avec légumes de saison',
    image: '/data/images/plat_agouti-roti-aux-epices.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm70',
    name: 'Couscous de Maïs aux Légumes',
    category: 'main',
    price: 3600,
    description: 'Couscous de maïs frais avec légumes mijotés et sauce arachides',
    image: '/data/images/plat_couscous-de-mais-aux-legumes.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm71',
    name: 'Poulet aux Légumes Camerounais',
    category: 'main',
    price: 4000,
    description: 'Poulet mijoté avec légumes frais du Cameroun et épices locales',
    image: '/data/images/plat_poulet-aux-legumes-camerounais.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm72',
    name: 'Riz aux Légumes Verts',
    category: 'main',
    price: 3200,
    description: 'Riz parfumé accompagné de légumes verts mijotés',
    image: '/data/images/plat_riz-aux-legumes-verts.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm73',
    name: 'Poisson aux Épices Traditionnelles',
    category: 'main',
    price: 4500,
    description: 'Poisson frais cuit aux épices traditionnelles camerounaises',
    image: '/data/images/plat_poisson-aux-epices-traditionnelles.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm74',
    name: 'Eru traditionnel',
    category: 'main',
    price: 2800,
    description: 'Épinards africains et viande braisée, saveur du Sud-Ouest.',
    image: '/data/images/plat_eru-traditionnel.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm75',
    name: 'Mbongo tchobi',
    category: 'main',
    price: 2700,
    description: 'Poisson noir au charbon d’épices, spécialité du Sanaga.',
    image: '/data/images/plat_mbongo.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm76',
    name: 'Sauce jaune',
    category: 'main',
    price: 2800,
    description: 'Poulet mijoté dans une sauce dorée et macabo vapeur.',
    image: '/data/images/plat_sauce-jaune.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm77',
    name: 'Kondré de porc',
    category: 'main',
    price: 3000,
    description: 'Plantain et porc braisé longuement dans son jus épicé.',
    image: '/data/images/plat_kondre.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm78',
    name: 'Folong sauté au poisson fumé',
    category: 'main',
    price: 2000,
    description: 'Feuilles vertes sautées à la tomate, poisson et oignons caramélisés.',
    image: '/data/images/plat_folong.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm79',
    name: 'Couscous maïs + gombo',
    category: 'main',
    price: 2200,
    description: 'Classique nordique servi chaud et consistant.',
    image: '/data/images/plat_coucous.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm80',
    name: 'Riz sauté à la camerounaise',
    category: 'main',
    price: 1800,
    description: 'Riz poêlé aux crevettes, légumes et œufs brouillés.',
    image: '/data/images/plat_riz-saute.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm81',
    name: 'Okok ',
    category: 'main',
    price: 2300,
    description: 'Légumes pâte d’arachide et bâton de manioc.',
    image: '/data/images/plat_okok.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm82',
    name: 'Soja grillé et plantain',
    category: 'main',
    price: 1500,
    description: 'Brochettes de tofu grillé, sauce piment et plantain frit.',
    image: '/data/images/plat_soja.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm83',
    name: 'Poisson braisé complet',
    category: 'main',
    price: 3500,
    description: 'Tilapia grillé servi avec banane et sauce tomate maison.',
    image: '/data/images/plat_poisson.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm84',
    name: 'Bouillon 237',
    category: 'main',
    price: 2500,
    description: 'Bouillon de bœuf pimenté, basilic et légumes frais.',
    image: '/data/images/plat_bouillon237.png',
    available: true,
    inStock: true,
  },

  // Drinks - Boissons
  {
    id: 'm9',
    name: 'Jus de Bissap Ngaoundéré',
    category: 'drink',
    price: 1000,
    description: 'Boisson rafraîchissante à l\'hibiscus rouge de Ngaoundéré',
    image: '/data/images/boisson_jus-de-bissap-ngaoundere.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm10',
    name: 'Jus de Gingembre Yaoundé',
    category: 'drink',
    price: 1200,
    description: 'Jus épicé au gingembre frais et citron, tradition de Yaoundé',
    image: '/data/images/boisson_jus-de-gingembre-yaounde.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm12',
    name: 'Bière Castel Blonde',
    category: 'drink',
    price: 1500,
    description: 'Bière locale camerounaise blonde, brassée au Cameroun',
    image: '/data/images/boisson_biere-castel-blonde.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm16',
    name: 'Jus de Safou Yaoundé',
    category: 'drink',
    price: 900,
    description: 'Boisson crémeuse au safou, fruit tropical de Yaoundé',
    image: '/data/images/boisson_jus-de-safou-yaounde.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm35',
    name: 'Jus de Mangue Fraîche',
    category: 'drink',
    price: 1000,
    description: 'Jus de mangue fraîchement pressée, sucrée naturellement',
    image: '/data/images/boisson_jus-de-mangue-fraiche.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm36',
    name: 'Jus d\'Ananas Kribi',
    category: 'drink',
    price: 1100,
    description: 'Jus d\'ananas frais de la région de Kribi',
    image: '/data/images/boisson_jus-d-ananas-kribi.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm37',
    name: 'Jus de Papaye',
    category: 'drink',
    price: 950,
    description: 'Jus rafraîchissant de papaye mûre du Cameroun',
    image: '/data/images/boisson_jus-de-papaye.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm39',
    name: 'Jus de Tamarind',
    category: 'drink',
    price: 1050,
    description: 'Boisson acidulée au tamarind, saveur authentique',
    image: '/data/images/boisson_jus-de-tamarind.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm40',
    name: 'Bière Castel Milk Stout',
    category: 'drink',
    price: 1500,
    description: 'Bière brune crémeuse, spécialité camerounaise',
    image: '/data/images/boisson_biere-castel-milk-stout.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm41',
    name: 'Jus de Fruit de la Passion',
    category: 'drink',
    price: 1300,
    description: 'Jus de fruit de la passion frais et acidulé',
    image: '/data/images/boisson_jus-de-fruit-de-la-passion.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm42',
    name: 'Eau de Coco Naturelle',
    category: 'drink',
    price: 800,
    description: 'Eau de coco fraîche directement de la noix',
    image: '/data/images/boisson_eau-de-coco-naturelle.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm52',
    name: 'Jus d\'Orange Pressée',
    category: 'drink',
    price: 900,
    description: 'Jus d\'orange fraîchement pressée, vitaminée',
    image: '/data/images/boisson_jus-d-orange-pressee.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm53',
    name: 'Thé Glacé au Citron',
    category: 'drink',
    price: 700,
    description: 'Thé glacé rafraîchissant au citron frais',
    image: '/data/images/boisson_the-glace-au-citron.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm54',
    name: 'Café Camerounais',
    category: 'drink',
    price: 600,
    description: 'Café arabica torréfié local, saveur authentique',
    image: '/data/images/boisson_cafe-camerounais.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm57',
    name: 'Jus de Banane Plantain',
    category: 'drink',
    price: 850,
    description: 'Jus de banane plantain mûre, naturellement sucré',
    image: '/data/images/boisson_jus-de-banane-plantain.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm58',
    name: 'Limonade Maison',
    category: 'drink',
    price: 750,
    description: 'Limonade fraîche préparée maison avec citron local',
    image: '/data/images/boisson_limonade-maison.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm59',
    name: 'Infusion de Menthe',
    category: 'drink',
    price: 650,
    description: 'Infusion rafraîchissante à la menthe fraîche',
    image: '/data/images/boisson_infusion-de-menthe.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm60',
    name: 'Jus de Carotte',
    category: 'drink',
    price: 950,
    description: 'Jus de carotte fraîche, riche en vitamines',
    image: '/data/images/boisson_jus-de-carotte.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm65',
    name: 'Smoothie Tropical',
    category: 'drink',
    price: 1400,
    description: 'Mélange de fruits tropicaux frais, banane, mangue et ananas',
    image: '/data/images/boisson_smoothie-tropical.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm66',
    name: 'Jus de Grenade',
    category: 'drink',
    price: 1200,
    description: 'Jus de grenade fraîche, antioxydant naturel',
    image: '/data/images/boisson_jus-de-grenade.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm67',
    name: 'Jus de citron vert',
    category: 'drink',
    price: 700,
    description: 'Rafraîchissant et désaltérant, parfait pour une pause.',
    image: '/data/images/boisson_jus-citron-vert.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm68',
    name: 'Jus de goyave',
    category: 'drink',
    price: 900,
    description: 'Sucré et parfumé, riche en vitamine C.',
    image: '/data/images/boisson_jus-goyave.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm69',
    name: 'Jus de pomme cannelle',
    category: 'drink',
    price: 1000,
    description: 'Alliance subtile de pomme fraîche et cannelle.',
    image: '/data/images/boisson_jus-pomme-cannelle.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm70',
    name: 'Jus de bissap menthe',
    category: 'drink',
    price: 1100,
    description: 'Bissap traditionnel relevé à la menthe fraîche.',
    image: '/data/images/boisson_jus-bissap-menthe.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm71',
    name: 'Jus de mangue passion',
    category: 'drink',
    price: 1300,
    description: 'Fusion exotique de mangue et fruit de la passion.',
    image: '/data/images/boisson_jus-mangue-passion.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm72',
    name: 'Jus de pastèque',
    category: 'drink',
    price: 800,
    description: 'Rafraîchissant et léger, idéal en été.',
    image: '/data/images/boisson_jus-pasteque.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm73',
    name: 'Jus de noix de coco',
    category: 'drink',
    price: 1200,
    description: 'Naturel et crémeux, directement de la noix.',
    image: '/data/images/boisson_jus-noix-coco.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm74',
    name: 'Jus de kaki',
    category: 'drink',
    price: 950,
    description: 'Sucré et velouté, une douceur automnale.',
    image: '/data/images/boisson_jus-kaki.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm75',
    name: 'Jus de prune',
    category: 'drink',
    price: 850,
    description: 'Acidulé et rafraîchissant, plein de saveurs.',
    image: '/data/images/boisson_jus-prune.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm76',
    name: 'Jus de raisin blanc',
    category: 'drink',
    price: 1000,
    description: 'Léger et fruité, parfait pour accompagner un repas.',
    image: '/data/images/boisson_jus-raisin-blanc.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm77',
    name: 'Jus de raisin rouge',
    category: 'drink',
    price: 1000,
    description: 'Corsé et savoureux, riche en antioxydants.',
    image: '/data/images/boisson_jus-raisin-rouge.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm78',
    name: 'Jus de pamplemousse',
    category: 'drink',
    price: 900,
    description: 'Amer et rafraîchissant, boost de vitamine C.',
    image: '/data/images/boisson_jus-pamplemousse.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm79',
    name: 'Jus de kiwi',
    category: 'drink',
    price: 1100,
    description: 'Acidulé et vitaminé, une explosion de fraîcheur.',
    image: '/data/images/boisson_jus-kiwi.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm80',
    name: 'Jus de poire',
    category: 'drink',
    price: 950,
    description: 'Doux et juteux, une saveur délicate.',
    image: '/data/images/boisson_jus-poire.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm81',
    name: 'Jus de pêche',
    category: 'drink',
    price: 1000,
    description: 'Sucré et parfumé, un classique estival.',
    image: '/data/images/boisson_jus-peche.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm82',
    name: 'Jus de myrtille',
    category: 'drink',
    price: 1200,
    description: 'Intense et antioxydant, riche en bienfaits.',
    image: '/data/images/boisson_jus-myrtille.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm83',
    name: 'Jus de cerise',
    category: 'drink',
    price: 1100,
    description: 'Sucré et acidulé, une touche de fête.',
    image: '/data/images/boisson_jus-cerise.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm84',
    name: 'Jus de framboise',
    category: 'drink',
    price: 1300,
    description: 'Délicat et parfumé, un plaisir raffiné.',
    image: '/data/images/boisson_jus-framboise.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm85',
    name: 'Jus de mûre',
    category: 'drink',
    price: 1150,
    description: 'Sauvage et intense, plein de caractère.',
    image: '/data/images/boisson_jus-mure.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm86',
    name: 'Jus de groseille',
    category: 'drink',
    price: 1050,
    description: 'Acidulé et vitaminé, une fraîcheur garantie.',
    image: '/data/images/boisson_jus-groseille.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm87',
    name: 'Jus de cassis',
    category: 'drink',
    price: 1250,
    description: 'Puissant et aromatique, riche en saveurs.',
    image: '/data/images/boisson_jus-cassis.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm88',
    name: 'Jus de litchi',
    category: 'drink',
    price: 1400,
    description: 'Exotique et sucré, une touche asiatique.',
    image: '/data/images/boisson_jus-litchi.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm89',
    name: 'Jus de longane',
    category: 'drink',
    price: 1350,
    description: 'Doux et parfumé, cousin du litchi.',
    image: '/data/images/boisson_jus-longane.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm90',
    name: 'Jus de ramboutan',
    category: 'drink',
    price: 1300,
    description: 'Exotique et juteux, une découverte unique.',
    image: '/data/images/boisson_jus-ramboutan.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm91',
    name: 'Jus de durian',
    category: 'drink',
    price: 1500,
    description: 'Puissant et crémeux, pour les amateurs.',
    image: '/data/images/boisson_jus-durian.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm92',
    name: 'Jus de mangoustan',
    category: 'drink',
    price: 1450,
    description: 'Acidulé et parfumé, reine des fruits.',
    image: '/data/images/boisson_jus-mangoustan.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm93',
    name: 'Jus de salak',
    category: 'drink',
    price: 1250,
    description: 'Acidulé et croquant, une saveur unique.',
    image: '/data/images/boisson_jus-salak.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm94',
    name: 'Jus de cempedak',
    category: 'drink',
    price: 1400,
    description: 'Sucré et crémeux, cousin du jacquier.',
    image: '/data/images/boisson_jus-cempedak.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm95',
    name: 'Jus de jacquier',
    category: 'drink',
    price: 1350,
    description: 'Sucré et parfumé, riche en fibres.',
    image: '/data/images/boisson_jus-jacquier.png',
    available: true,
    inStock: true,
  },
  {
    id: 'm96',
    name: 'Jus de nèfle du Japon',
    category: 'drink',
    price: 1200,
    description: 'Acidulé et rafraîchissant, une douceur japonaise.',
    image: '/data/images/boisson_jus-nefle-japon.png',
    available: true,
    inStock: true,
  },
];

export const mockOrders: Order[] = [];

export const mockComplaints: Complaint[] = [];

export const mockEvents: Event[] = [
  {
    id: 'e1',
    name: 'Soirée Dégustation de Vins',
    description: 'Rejoignez-nous pour une dégustation exclusive de vins',
    date: new Date('2025-11-15T19:00:00'),
    participants: [],
    maxParticipants: 20,
  },
  {
    id: 'e2',
    name: 'Atelier de Cuisine',
    description: 'Apprenez à cuisiner la cuisine française avec notre chef',
    date: new Date('2025-11-22T14:00:00'),
    participants: [],
    maxParticipants: 15,
  },
];

export const mockEmployees: Employee[] = [
  {
    id: 'emp1',
    firstName: 'Pierre',
    lastName: 'Dubois',
    position: 'cook',
    status: 'active',
    email: 'pierre@zeduc.employe.com',
    phone: '+237 6 23 45 67 89',
    hireDate: new Date('2023-01-15'),
  },
  {
    id: 'emp2',
    firstName: 'Marie',
    lastName: 'Martin',
    position: 'server',
    status: 'active',
    email: 'marie@zeduc.employe.com',
    phone: '+237 6 23 45 67 90',
    hireDate: new Date('2023-06-01'),
  },
  {
    id: 'emp3',
    firstName: 'Luc',
    lastName: 'Bernard',
    position: 'delivery',
    status: 'on-leave',
    email: 'luc@zeduc.employe.com',
    phone: '+237 6 23 45 67 91',
    hireDate: new Date('2024-03-10'),
  },
];